# version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - http-volume:/var/www/html
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    # Run as root user to avoid permission issues with bind mounts
    user: root
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - http-volume:/var/www/html
    env_file: .env
    restart: on-failure
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: on-failure

volumes:
  http-volume:
    driver: local
    driver_opts:
      type: none
      o: bind,rw
      device: ${HOME}/data/wordpress
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge