# version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - http-volume:/var/www/html

  wordpress:
    build:
      context: ./requirements/wordpress
    expose:
      - "9000"
    volumes:
      - http-volume:/var/www/html

volumes:
  http-volume:
