# version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - http-volume:/var/www/html
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - http-volume:/var/www/html
    env_file: .env
    secrets:
      - db_password
      - credentials
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/credentials
    restart: on-failure
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: on-failure

volumes:
  http-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt